// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'truda_database/entity/truda_aic_entity.dart';
import 'truda_database/entity/truda_call_entity.dart';
import 'truda_database/entity/truda_conversation_entity.dart';
import 'truda_database/entity/truda_her_entity.dart';
import 'truda_database/entity/truda_msg_entity.dart';
import 'truda_database/entity/truda_order_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8011743449502788865),
      name: 'NewHitaOrderEntity',
      lastPropertyId: const IdUid(13, 1084287523106078823),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 642414519732763209),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7817396071384778639),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1191431334117814947),
            name: 'orderNo',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3255813745501476692),
            name: 'productId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6261159846272226489),
            name: 'price',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8407209225517329965),
            name: 'currency',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 849222018351143349),
            name: 'payType',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 3742573523255122338),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4817762745647518341),
            name: 'payTime',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 3986802103244211821),
            name: 'orderCreateTime',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 4511277429801036804),
            name: 'orderStatus',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 1833682492766489766),
            name: 'isUploadServer',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 1084287523106078823),
            name: 'dateInsert',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 3805373095646452966),
      name: 'TrudaAicEntity',
      lastPropertyId: const IdUid(17, 2647131036916114003),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7856959129817311680),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5611018491768706827),
            name: 'extra',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1746920603356043267),
            name: 'callCardCount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3717478548024524707),
            name: 'aicId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3246693833449334822),
            name: 'isOnline',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2204285593977665418),
            name: 'muteStatus',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7575297668125438412),
            name: 'isCard',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8701652221807249190),
            name: 'propDuration',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7640500554494672864),
            name: 'isFollowed',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7097735582710237545),
            name: 'nickname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 4846403542995221105),
            name: 'filename',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 8613647205509637617),
            name: 'portrait',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6389243822872042755),
            name: 'localPath',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 2199967605032633340),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 2224908191045833463),
            name: 'dateInsert',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 147237444541340145),
            name: 'playState',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 2647131036916114003),
            name: 'rawData',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 8823838551256505320),
      name: 'TrudaCallEntity',
      lastPropertyId: const IdUid(11, 8706942052677882714),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6068340734646988744),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1399849522160356319),
            name: 'dateInsert',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8185899016662409520),
            name: 'channelId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3110457992702804807),
            name: 'myId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 632545629291000008),
            name: 'herId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 324793735357413638),
            name: 'herVirtualId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 9023268192945736904),
            name: 'groupId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 2404546296950778388),
            name: 'callType',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3652679496526549570),
            name: 'callStatus',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 6697582685773870538),
            name: 'duration',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 8706942052677882714),
            name: 'extra',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3981016490832375109),
      name: 'TrudaConversationEntity',
      lastPropertyId: const IdUid(13, 3206095127119758667),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1464711531386791209),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7318497797913268900),
            name: 'dateInsert',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4064802360100373060),
            name: 'msgId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 7422860143406645230)),
        ModelProperty(
            id: const IdUid(4, 8594292861760842770),
            name: 'myId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 51409630009236967),
            name: 'herId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8037045544453416173),
            name: 'groupId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(2, 5285539888305902585)),
        ModelProperty(
            id: const IdUid(7, 1825033768609721540),
            name: 'sendType',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7648485577564563033),
            name: 'sendState',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 5990236127597754457),
            name: 'unReadQuality',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2077698257020924650),
            name: 'top',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2925151804040525523),
            name: 'content',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 750370616507060238),
            name: 'lastMsgType',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 3206095127119758667),
            name: 'rawData',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 8987814655464445906),
      name: 'TrudaHerEntity',
      lastPropertyId: const IdUid(5, 9118305814314619878),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1317843489033138714),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8484027969507940392),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 8640937974852068476)),
        ModelProperty(
            id: const IdUid(3, 6271279590677850241),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1866176410187193190),
            name: 'portrait',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 9118305814314619878),
            name: 'date',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 3221702756539978290),
      name: 'TrudaMsgEntity',
      lastPropertyId: const IdUid(13, 2900050476479670386),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 9155093401120723890),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5657155416628114367),
            name: 'dateInsert',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 250550266309476721),
            name: 'msgId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(4, 7233354933184401396)),
        ModelProperty(
            id: const IdUid(4, 4700774629353783816),
            name: 'myId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(5, 1663620508424196793)),
        ModelProperty(
            id: const IdUid(5, 1968854183934034644),
            name: 'herId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5488086892859015784),
            name: 'groupId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 3048958916390600660),
            name: 'sendType',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8232841842869907577),
            name: 'sendState',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 832051617979457035),
            name: 'readState',
            type: 2,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7186043887753179000),
            name: 'msgType',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 1869316001830391074),
            name: 'content',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 8332030326272415343),
            name: 'extra',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 2900050476479670386),
            name: 'rawData',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(6, 3221702756539978290),
      lastIndexId: const IdUid(5, 1663620508424196793),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    NewHitaOrderEntity: EntityDefinition<NewHitaOrderEntity>(
        model: _entities[0],
        toOneRelations: (NewHitaOrderEntity object) => [],
        toManyRelations: (NewHitaOrderEntity object) => {},
        getId: (NewHitaOrderEntity object) => object.id,
        setId: (NewHitaOrderEntity object, int id) {
          object.id = id;
        },
        objectToFB: (NewHitaOrderEntity object, fb.Builder fbb) {
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final orderNoOffset =
              object.orderNo == null ? null : fbb.writeString(object.orderNo!);
          final productIdOffset = object.productId == null
              ? null
              : fbb.writeString(object.productId!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final currencyOffset = object.currency == null
              ? null
              : fbb.writeString(object.currency!);
          final payTypeOffset =
              object.payType == null ? null : fbb.writeString(object.payType!);
          final typeOffset =
              object.type == null ? null : fbb.writeString(object.type!);
          final payTimeOffset =
              object.payTime == null ? null : fbb.writeString(object.payTime!);
          final orderCreateTimeOffset = object.orderCreateTime == null
              ? null
              : fbb.writeString(object.orderCreateTime!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, orderNoOffset);
          fbb.addOffset(3, productIdOffset);
          fbb.addOffset(4, priceOffset);
          fbb.addOffset(5, currencyOffset);
          fbb.addOffset(6, payTypeOffset);
          fbb.addOffset(7, typeOffset);
          fbb.addOffset(8, payTimeOffset);
          fbb.addOffset(9, orderCreateTimeOffset);
          fbb.addInt64(10, object.orderStatus);
          fbb.addBool(11, object.isUploadServer);
          fbb.addInt64(12, object.dateInsert);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = NewHitaOrderEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              orderNo: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              productId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              price: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              currency: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              payType: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              type: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              payTime:
                  const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 20),
              orderCreateTime: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              dateInsert: const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0))
            ..orderStatus =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24)
            ..isUploadServer = const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 26);

          return object;
        }),
    TrudaAicEntity: EntityDefinition<TrudaAicEntity>(
        model: _entities[1],
        toOneRelations: (TrudaAicEntity object) => [],
        toManyRelations: (TrudaAicEntity object) => {},
        getId: (TrudaAicEntity object) => object.id,
        setId: (TrudaAicEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TrudaAicEntity object, fb.Builder fbb) {
          final extraOffset =
              object.extra == null ? null : fbb.writeString(object.extra!);
          final nicknameOffset = object.nickname == null
              ? null
              : fbb.writeString(object.nickname!);
          final filenameOffset = object.filename == null
              ? null
              : fbb.writeString(object.filename!);
          final portraitOffset = object.portrait == null
              ? null
              : fbb.writeString(object.portrait!);
          final localPathOffset = object.localPath == null
              ? null
              : fbb.writeString(object.localPath!);
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final rawDataOffset = fbb.writeString(object.rawData);
          fbb.startTable(18);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, extraOffset);
          fbb.addInt64(2, object.callCardCount);
          fbb.addInt64(3, object.aicId);
          fbb.addInt64(4, object.isOnline);
          fbb.addInt64(5, object.muteStatus);
          fbb.addInt64(6, object.isCard);
          fbb.addInt64(7, object.propDuration);
          fbb.addBool(8, object.isFollowed);
          fbb.addOffset(9, nicknameOffset);
          fbb.addOffset(10, filenameOffset);
          fbb.addOffset(11, portraitOffset);
          fbb.addOffset(12, localPathOffset);
          fbb.addOffset(13, userIdOffset);
          fbb.addInt64(14, object.dateInsert);
          fbb.addInt64(15, object.playState);
          fbb.addOffset(16, rawDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TrudaAicEntity(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0))
            ..extra = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..callCardCount =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8)
            ..aicId =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10)
            ..isOnline =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12)
            ..muteStatus =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14)
            ..isCard =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..propDuration =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18)
            ..isFollowed =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 20)
            ..nickname = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..filename = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 24)
            ..portrait = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26)
            ..localPath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 28)
            ..userId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 30)
            ..playState =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0)
            ..rawData = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 36, '');

          return object;
        }),
    TrudaCallEntity: EntityDefinition<TrudaCallEntity>(
        model: _entities[2],
        toOneRelations: (TrudaCallEntity object) => [],
        toManyRelations: (TrudaCallEntity object) => {},
        getId: (TrudaCallEntity object) => object.id,
        setId: (TrudaCallEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TrudaCallEntity object, fb.Builder fbb) {
          final channelIdOffset = fbb.writeString(object.channelId);
          final myIdOffset = fbb.writeString(object.myId);
          final herIdOffset = fbb.writeString(object.herId);
          final herVirtualIdOffset = fbb.writeString(object.herVirtualId);
          final groupIdOffset = fbb.writeString(object.groupId);
          final durationOffset = fbb.writeString(object.duration);
          final extraOffset = fbb.writeString(object.extra);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dateInsert);
          fbb.addOffset(2, channelIdOffset);
          fbb.addOffset(3, myIdOffset);
          fbb.addOffset(4, herIdOffset);
          fbb.addOffset(5, herVirtualIdOffset);
          fbb.addOffset(6, groupIdOffset);
          fbb.addInt8(7, object.callType);
          fbb.addInt64(8, object.callStatus);
          fbb.addOffset(9, durationOffset);
          fbb.addOffset(10, extraOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TrudaCallEntity(
              myId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              herId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              herVirtualId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              channelId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              callType:
                  const fb.Int8Reader().vTableGet(buffer, rootOffset, 18, 0),
              callStatus:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
              dateInsert:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              duration: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              extra:
                  const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 24, ''))
            ..groupId = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 16, '');

          return object;
        }),
    TrudaConversationEntity: EntityDefinition<TrudaConversationEntity>(
        model: _entities[3],
        toOneRelations: (TrudaConversationEntity object) => [],
        toManyRelations: (TrudaConversationEntity object) => {},
        getId: (TrudaConversationEntity object) => object.id,
        setId: (TrudaConversationEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TrudaConversationEntity object, fb.Builder fbb) {
          final msgIdOffset = fbb.writeString(object.msgId);
          final myIdOffset = fbb.writeString(object.myId);
          final herIdOffset = fbb.writeString(object.herId);
          final groupIdOffset = fbb.writeString(object.groupId);
          final contentOffset = fbb.writeString(object.content);
          final rawDataOffset = fbb.writeString(object.rawData);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dateInsert);
          fbb.addOffset(2, msgIdOffset);
          fbb.addOffset(3, myIdOffset);
          fbb.addOffset(4, herIdOffset);
          fbb.addOffset(5, groupIdOffset);
          fbb.addInt8(6, object.sendType);
          fbb.addInt8(7, object.sendState);
          fbb.addInt64(8, object.unReadQuality);
          fbb.addInt64(9, object.top);
          fbb.addOffset(10, contentOffset);
          fbb.addInt64(11, object.lastMsgType);
          fbb.addOffset(12, rawDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TrudaConversationEntity(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 16, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              lastMsgType:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
              sendState:
                  const fb.Int8Reader().vTableGet(buffer, rootOffset, 18, 0),
              unReadQuality:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
              top: const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0))
            ..msgId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..groupId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '');

          return object;
        }),
    TrudaHerEntity: EntityDefinition<TrudaHerEntity>(
        model: _entities[4],
        toOneRelations: (TrudaHerEntity object) => [],
        toManyRelations: (TrudaHerEntity object) => {},
        getId: (TrudaHerEntity object) => object.id,
        setId: (TrudaHerEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TrudaHerEntity object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset = fbb.writeString(object.name);
          final portraitOffset = object.portrait == null
              ? null
              : fbb.writeString(object.portrait!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, portraitOffset);
          fbb.addInt64(4, object.date.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TrudaHerEntity(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              portrait: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              date: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)));

          return object;
        }),
    TrudaMsgEntity: EntityDefinition<TrudaMsgEntity>(
        model: _entities[5],
        toOneRelations: (TrudaMsgEntity object) => [],
        toManyRelations: (TrudaMsgEntity object) => {},
        getId: (TrudaMsgEntity object) => object.id,
        setId: (TrudaMsgEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TrudaMsgEntity object, fb.Builder fbb) {
          final msgIdOffset = fbb.writeString(object.msgId);
          final myIdOffset = fbb.writeString(object.myId);
          final herIdOffset = fbb.writeString(object.herId);
          final groupIdOffset = fbb.writeString(object.groupId);
          final contentOffset = fbb.writeString(object.content);
          final extraOffset =
              object.extra == null ? null : fbb.writeString(object.extra!);
          final rawDataOffset = fbb.writeString(object.rawData);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dateInsert);
          fbb.addOffset(2, msgIdOffset);
          fbb.addOffset(3, myIdOffset);
          fbb.addOffset(4, herIdOffset);
          fbb.addOffset(5, groupIdOffset);
          fbb.addInt8(6, object.sendType);
          fbb.addInt8(7, object.sendState);
          fbb.addInt8(8, object.readState);
          fbb.addInt64(9, object.msgType);
          fbb.addOffset(10, contentOffset);
          fbb.addOffset(11, extraOffset);
          fbb.addOffset(12, rawDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TrudaMsgEntity(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 16, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, ''),
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              sendState:
                  const fb.Int8Reader().vTableGet(buffer, rootOffset, 18, 0),
              readState:
                  const fb.Int8Reader().vTableGet(buffer, rootOffset, 20, 0))
            ..msgId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..groupId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..extra = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [NewHitaOrderEntity] entity fields to define ObjectBox queries.
class NewHitaOrderEntity_ {
  /// see [NewHitaOrderEntity.id]
  static final id =
      QueryIntegerProperty<NewHitaOrderEntity>(_entities[0].properties[0]);

  /// see [NewHitaOrderEntity.userId]
  static final userId =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[1]);

  /// see [NewHitaOrderEntity.orderNo]
  static final orderNo =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[2]);

  /// see [NewHitaOrderEntity.productId]
  static final productId =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[3]);

  /// see [NewHitaOrderEntity.price]
  static final price =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[4]);

  /// see [NewHitaOrderEntity.currency]
  static final currency =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[5]);

  /// see [NewHitaOrderEntity.payType]
  static final payType =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[6]);

  /// see [NewHitaOrderEntity.type]
  static final type =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[7]);

  /// see [NewHitaOrderEntity.payTime]
  static final payTime =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[8]);

  /// see [NewHitaOrderEntity.orderCreateTime]
  static final orderCreateTime =
      QueryStringProperty<NewHitaOrderEntity>(_entities[0].properties[9]);

  /// see [NewHitaOrderEntity.orderStatus]
  static final orderStatus =
      QueryIntegerProperty<NewHitaOrderEntity>(_entities[0].properties[10]);

  /// see [NewHitaOrderEntity.isUploadServer]
  static final isUploadServer =
      QueryBooleanProperty<NewHitaOrderEntity>(_entities[0].properties[11]);

  /// see [NewHitaOrderEntity.dateInsert]
  static final dateInsert =
      QueryIntegerProperty<NewHitaOrderEntity>(_entities[0].properties[12]);
}

/// [TrudaAicEntity] entity fields to define ObjectBox queries.
class TrudaAicEntity_ {
  /// see [TrudaAicEntity.id]
  static final id =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[0]);

  /// see [TrudaAicEntity.extra]
  static final extra =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[1]);

  /// see [TrudaAicEntity.callCardCount]
  static final callCardCount =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[2]);

  /// see [TrudaAicEntity.aicId]
  static final aicId =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[3]);

  /// see [TrudaAicEntity.isOnline]
  static final isOnline =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[4]);

  /// see [TrudaAicEntity.muteStatus]
  static final muteStatus =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[5]);

  /// see [TrudaAicEntity.isCard]
  static final isCard =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[6]);

  /// see [TrudaAicEntity.propDuration]
  static final propDuration =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[7]);

  /// see [TrudaAicEntity.isFollowed]
  static final isFollowed =
      QueryBooleanProperty<TrudaAicEntity>(_entities[1].properties[8]);

  /// see [TrudaAicEntity.nickname]
  static final nickname =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[9]);

  /// see [TrudaAicEntity.filename]
  static final filename =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[10]);

  /// see [TrudaAicEntity.portrait]
  static final portrait =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[11]);

  /// see [TrudaAicEntity.localPath]
  static final localPath =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[12]);

  /// see [TrudaAicEntity.userId]
  static final userId =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[13]);

  /// see [TrudaAicEntity.dateInsert]
  static final dateInsert =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[14]);

  /// see [TrudaAicEntity.playState]
  static final playState =
      QueryIntegerProperty<TrudaAicEntity>(_entities[1].properties[15]);

  /// see [TrudaAicEntity.rawData]
  static final rawData =
      QueryStringProperty<TrudaAicEntity>(_entities[1].properties[16]);
}

/// [TrudaCallEntity] entity fields to define ObjectBox queries.
class TrudaCallEntity_ {
  /// see [TrudaCallEntity.id]
  static final id =
      QueryIntegerProperty<TrudaCallEntity>(_entities[2].properties[0]);

  /// see [TrudaCallEntity.dateInsert]
  static final dateInsert =
      QueryIntegerProperty<TrudaCallEntity>(_entities[2].properties[1]);

  /// see [TrudaCallEntity.channelId]
  static final channelId =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[2]);

  /// see [TrudaCallEntity.myId]
  static final myId =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[3]);

  /// see [TrudaCallEntity.herId]
  static final herId =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[4]);

  /// see [TrudaCallEntity.herVirtualId]
  static final herVirtualId =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[5]);

  /// see [TrudaCallEntity.groupId]
  static final groupId =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[6]);

  /// see [TrudaCallEntity.callType]
  static final callType =
      QueryIntegerProperty<TrudaCallEntity>(_entities[2].properties[7]);

  /// see [TrudaCallEntity.callStatus]
  static final callStatus =
      QueryIntegerProperty<TrudaCallEntity>(_entities[2].properties[8]);

  /// see [TrudaCallEntity.duration]
  static final duration =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[9]);

  /// see [TrudaCallEntity.extra]
  static final extra =
      QueryStringProperty<TrudaCallEntity>(_entities[2].properties[10]);
}

/// [TrudaConversationEntity] entity fields to define ObjectBox queries.
class TrudaConversationEntity_ {
  /// see [TrudaConversationEntity.id]
  static final id =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[0]);

  /// see [TrudaConversationEntity.dateInsert]
  static final dateInsert =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[1]);

  /// see [TrudaConversationEntity.msgId]
  static final msgId =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[2]);

  /// see [TrudaConversationEntity.myId]
  static final myId =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[3]);

  /// see [TrudaConversationEntity.herId]
  static final herId =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[4]);

  /// see [TrudaConversationEntity.groupId]
  static final groupId =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[5]);

  /// see [TrudaConversationEntity.sendType]
  static final sendType =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[6]);

  /// see [TrudaConversationEntity.sendState]
  static final sendState =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[7]);

  /// see [TrudaConversationEntity.unReadQuality]
  static final unReadQuality =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[8]);

  /// see [TrudaConversationEntity.top]
  static final top =
      QueryIntegerProperty<TrudaConversationEntity>(_entities[3].properties[9]);

  /// see [TrudaConversationEntity.content]
  static final content =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[10]);

  /// see [TrudaConversationEntity.lastMsgType]
  static final lastMsgType = QueryIntegerProperty<TrudaConversationEntity>(
      _entities[3].properties[11]);

  /// see [TrudaConversationEntity.rawData]
  static final rawData =
      QueryStringProperty<TrudaConversationEntity>(_entities[3].properties[12]);
}

/// [TrudaHerEntity] entity fields to define ObjectBox queries.
class TrudaHerEntity_ {
  /// see [TrudaHerEntity.id]
  static final id =
      QueryIntegerProperty<TrudaHerEntity>(_entities[4].properties[0]);

  /// see [TrudaHerEntity.uid]
  static final uid =
      QueryStringProperty<TrudaHerEntity>(_entities[4].properties[1]);

  /// see [TrudaHerEntity.name]
  static final name =
      QueryStringProperty<TrudaHerEntity>(_entities[4].properties[2]);

  /// see [TrudaHerEntity.portrait]
  static final portrait =
      QueryStringProperty<TrudaHerEntity>(_entities[4].properties[3]);

  /// see [TrudaHerEntity.date]
  static final date =
      QueryIntegerProperty<TrudaHerEntity>(_entities[4].properties[4]);
}

/// [TrudaMsgEntity] entity fields to define ObjectBox queries.
class TrudaMsgEntity_ {
  /// see [TrudaMsgEntity.id]
  static final id =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[0]);

  /// see [TrudaMsgEntity.dateInsert]
  static final dateInsert =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[1]);

  /// see [TrudaMsgEntity.msgId]
  static final msgId =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[2]);

  /// see [TrudaMsgEntity.myId]
  static final myId =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[3]);

  /// see [TrudaMsgEntity.herId]
  static final herId =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[4]);

  /// see [TrudaMsgEntity.groupId]
  static final groupId =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[5]);

  /// see [TrudaMsgEntity.sendType]
  static final sendType =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[6]);

  /// see [TrudaMsgEntity.sendState]
  static final sendState =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[7]);

  /// see [TrudaMsgEntity.readState]
  static final readState =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[8]);

  /// see [TrudaMsgEntity.msgType]
  static final msgType =
      QueryIntegerProperty<TrudaMsgEntity>(_entities[5].properties[9]);

  /// see [TrudaMsgEntity.content]
  static final content =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[10]);

  /// see [TrudaMsgEntity.extra]
  static final extra =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[11]);

  /// see [TrudaMsgEntity.rawData]
  static final rawData =
      QueryStringProperty<TrudaMsgEntity>(_entities[5].properties[12]);
}
